## Credit Card Fraud Detection Project

More info on this project can be found in the README file as well as the R script (where most of the actual work was done for this project)

Importing any of the packages that I might end up using

In [31]:
import pandas as pd
import seaborn as sns
import numpy as np
%matplotlib inline
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import linear_model
import numpy as np
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score, roc_auc_score, roc_curve, accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.neighbors import KNeighborsClassifier

In [4]:
#importing the data
credit = pd.read_csv("CCFraud.csv")
credit.head()

Unnamed: 0        V1        V2        V3        V4        V5        V6  \
0           1 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1           2  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2           3 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3           4 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4           5 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   

         V7        V8        V9  ...       V21       V22       V23       V24  \
0  0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928   
1 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575   
4  0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

Data cleaning in order to fit different classification models (Logistic Regression, Random Forest, Gradient Boosting, Support Vector Machines, KNN)

In [6]:
cc = credit.dropna()

In [7]:
X = cc.iloc[:,0:29]
y = cc.iloc[:,30]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)

In [13]:
log_model = LogisticRegression(max_iter = 4000)
log_model.fit(X_train, y_train)
yhatlog = log_model.predict(X_test)

In [17]:
forest = RandomForestClassifier()
forest.fit(X_train, y_train)

In [24]:
yhatforest = forest.predict(X_test)

In [21]:
gbm = GradientBoostingClassifier()
gbm.fit(X_train, y_train)

In [25]:
yhatgbm = gbm.predict(X_test)

In [28]:
supportvector = SVC()
supportvector.fit(X_train, y_train)
yhatvector = supportvector.predict(X_test)

In [37]:
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(X_train, y_train)
yhatknn = knn.predict(X_test)

In [20]:
print(accuracy_score(y_test, yhatlog))
print(f1_score(y_test, yhatlog))
print(precision_score(y_test, yhatlog))
print(recall_score(y_test, yhatlog))
print(roc_auc_score(y_test, yhatlog))
confusion_matrix(y_test, yhatlog)

0.9990344270641316
0.6927374301675977
0.7948717948717948
0.6138613861386139
0.8067899966218922


array([[56844,    16],
       [   39,    62]], dtype=int64)

In [26]:
print(accuracy_score(y_test, yhatforest))
print(f1_score(y_test, yhatforest))
print(precision_score(y_test, yhatforest))
print(recall_score(y_test, yhatforest))
print(roc_auc_score(y_test, yhatforest))
confusion_matrix(y_test, yhatforest)

0.999490879724724
0.8415300546448087
0.9390243902439024
0.7623762376237624
0.881144151172064


array([[56855,     5],
       [   24,    77]], dtype=int64)

In [27]:
print(accuracy_score(y_test, yhatgbm))
print(f1_score(y_test, yhatgbm))
print(precision_score(y_test, yhatgbm))
print(recall_score(y_test, yhatgbm))
print(roc_auc_score(y_test, yhatgbm))
confusion_matrix(y_test, yhatgbm)

0.9991748740366215
0.7486631016042781
0.813953488372093
0.693069306930693
0.8463939570179319


array([[56844,    16],
       [   31,    70]], dtype=int64)

In [39]:
print(accuracy_score(y_test, yhatknn))
print(f1_score(y_test, yhatknn))
print(precision_score(y_test, yhatknn))
print(recall_score(y_test, yhatknn))
print(roc_auc_score(y_test, yhatknn))
confusion_matrix(y_test, yhatknn)

0.9985428626604168
0.39416058394160586
0.75
0.26732673267326734
0.6335842245849629


array([[56851,     9],
       [   74,    27]], dtype=int64)

See the R file for the EDA and most of the actual project work. I just used Python to fit some of the models since I prefer Sklearn when it comes to quickly fitting machine learning models.